spring:
    datasource:
        url: jdbc:mysql://localhost:3306/eCine?autoreconnect=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.MySQL5Dialect
        database: mysql
        database-platform: MYSQL
flyway : 
  url : jdbc:mysql://localhost:3306/mysql
  schemas : eCine
  user : root
  password :        
        
